version: "3.8"

services:
  api_dev:
    container_name: api_dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./env/api_dev.env
    depends_on:
      - db_dev

  db_dev:
    container_name: db_dev
    image: postgres:13
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    env_file:
      - ./env/db_dev.env

volumes:
  db_data_dev: